### ISSUE TITLE
Error: document upload

### ISSUE THREAD

**Issue by benson173** [mckaywrigley/chatbot-ui#1380] opened 2024-02-05 08:04 UTC
Hi, I encounter the error message when I upload the pdf document.

./node_modules/@xenova/transformers/node_modules/sharp/build/Release/sharp-darwin-x64.node
Module parse failed: Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)

**Comment by siavashvj** [comment] 2024-02-05 15:23
Dupe of this probably: https://github.com/mckaywrigley/chatbot-ui/issues/1156

(FIles with filenames containing non-standard english characters fail to upload. Rename your file.)

**Comment by mckaywrigley** [comment] 2024-02-06 00:21
Just merged a PR that should handle weird character issues in file naming!

**Closed as completed by mckaywrigley** 2024-02-06 00:21 UTC
