### ISSUE TITLE
Application error: a server-side exception has occurred (see the server logs for more information). Digest: 3850701382

### ISSUE THREAD

**Issue by 520qianjiawen** [mckaywrigley/chatbot-ui#1227] opened 2024-01-22 04:51 UTC

**Comment by xycjscs** [comment] 2024-01-22 15:39
usually it means the website was not connected to a proper database, or the database was not upgraded to tools compatible version. Tools version needs tool, assistant and other new tables.

**Comment by Itangalo** [comment] 2024-01-23 12:42
I'm getting the same issue when trying to install using Vercel. Is there a description of how to make things work with Vercel, or is that method now broken?

**Comment by Itangalo** [comment] 2024-01-23 12:46
Duplicate of #1220. I suggest closing this issue.

**Closed as completed** 2024-01-23 20:31 UTC
